import type { SearchEntryType } from "@/lib/search-index";

/**
 * Curated bilingual index of every navigable page on the site
 * (plus quick actions) for the site-wide search system.
 */

export interface StaticPageDef {
  href: string;
  titleBn: string;
  titleEn: string;
  excerptBn: string;
  excerptEn: string;
  keywords: string;
  type: SearchEntryType;
}

export const STATIC_PAGES: StaticPageDef[] = [
  {
    href: "/about",
    type: "page",
    titleBn: "আমাদের সম্পর্কে",
    titleEn: "About the Institute",
    excerptBn: "প্রতিষ্ঠান পরিচিতি, লক্ষ্য ও ১৪টি উদ্দেশ্য",
    excerptEn: "Institute introduction, vision and 14 objectives",
    keywords: "about parichiti vision objectives lakho uddeshyo history foundation",
  },
  {
    href: "/about/leadership",
    type: "page",
    titleBn: "নেতৃত্ব ও প্রশাসন",
    titleEn: "Leadership & Administration",
    excerptBn: "মুহতামিম, শিক্ষা সচিব ও পরিচালক পরিষদ",
    excerptEn: "Principal, education secretary and directorate",
    keywords: "leadership muhtamim director chairman admin netritvo",
  },
  {
    href: "/about/campus",
    type: "page",
    titleBn: "ক্যাম্পাস ও সুবিধাসমূহ",
    titleEn: "Campus & Facilities",
    excerptBn: "লাইব্রেরি, আবাসন, মসজিদ ও ঠিকানা",
    excerptEn: "Library, accommodation, mosque and address",
    keywords: "campus facilities library hostel mosque address map badda satarkul",
  },
  {
    href: "/about/alumni",
    type: "page",
    titleBn: "অ্যালামনাই অ্যাসোসিয়েশন",
    titleEn: "Alumni Association",
    excerptBn: "প্রাক্তন শিক্ষার্থীদের ব্যাচ পরিসংখ্যান ও কার্যক্রম",
    excerptEn: "Alumni batch statistics and engagement",
    keywords: "alumni prakkonthi batch graduates association",
  },
  {
    href: "/academics",
    type: "page",
    titleBn: "একাডেমিক পরিচিতি",
    titleEn: "Academics Overview",
    excerptBn: "কোর্স কাঠামো, বিভাগ ও উন্নয়ন কার্যক্রম",
    excerptEn: "Course structure, departments and development programs",
    keywords: "academics courses ekademyik department",
  },
  {
    href: "/academics/courses",
    type: "page",
    titleBn: "চলমান কোর্সসমূহ",
    titleEn: "Current Courses",
    excerptBn: "৭টি কোর্সের সম্পূর্ণ তালিকা ও বিবরণ",
    excerptEn: "Full catalog of the 7 running courses",
    keywords: "courses list catalog cholmono",
  },
  {
    href: "/academics/faculty",
    type: "page",
    titleBn: "শিক্ষক ও গবেষকবৃন্দ",
    titleEn: "Faculty & Researchers",
    excerptBn: "উস্তাজ ও গবেষকদের পরিচিতি ও বিষয়",
    excerptEn: "Ustadhs and researchers with their subjects",
    keywords: "faculty teachers ustadh shikkok gobeshok",
  },
  {
    href: "/academics/development",
    type: "page",
    titleBn: "শিক্ষার্থী উন্নয়ন কার্যক্রম (SDP)",
    titleEn: "Student Development Program",
    excerptBn: "তারবিয়াহ, দাওয়াহ প্রশিক্ষণসহ ৬টি বাধ্যতামূলক কার্যক্রম",
    excerptEn: "6 mandatory programs incl. tarbiyah and dawah training",
    keywords: "sdp development tarbiyah unnayon training",
  },
  {
    href: "/academics/downloads",
    type: "page",
    titleBn: "ডাউনলোড সেন্টার",
    titleEn: "Download Center",
    excerptBn: "প্রসপেক্টাস, সিলেবাস ও ফরমসমূহ",
    excerptEn: "Prospectus, syllabus and forms",
    keywords: "download prospectus syllabus form pdf download center",
  },
  {
    href: "/admissions",
    type: "page",
    titleBn: "ভর্তি প্রক্রিয়া",
    titleEn: "Admissions Process",
    excerptBn: "৫ ধাপের ভর্তি প্রক্রিয়া ও প্রবেশিকা পরীক্ষা",
    excerptEn: "5-step admission process and entry test",
    keywords: "admission bhorthi process apply step exam prosheka",
  },
  {
    href: "/admissions/scholarships",
    type: "page",
    titleBn: "স্কলারশিপ ও আর্থিক সহায়তা",
    titleEn: "Scholarships & Financial Aid",
    excerptBn: "শতভাগ বৃত্তিসহ আবাসন, খাবার ও ভাতা",
    excerptEn: "Full scholarship incl. housing, meals and stipend",
    keywords: "scholarship britto financial aid sthapito free bhorti",
  },
  {
    href: "/admissions/faq",
    type: "page",
    titleBn: "ভর্তি সংক্রান্ত সচরাচর জিজ্ঞাসা",
    titleEn: "Admissions FAQ",
    excerptBn: "ভর্তি, থাকা-খাওয়া ও কোর্স নিয়ে প্রশ্নোত্তর",
    excerptEn: "Q&A about admission, accommodation and courses",
    keywords: "faq prosno uttor admission questions",
  },
  {
    href: "/research",
    type: "page",
    titleBn: "গবেষণা ও প্রকাশনা",
    titleEn: "Research & Publications",
    excerptBn: "গবেষণা অধিদপ্তরের কার্যক্রম ও বিভাগসমূহ",
    excerptEn: "Research division activities and tracks",
    keywords: " research gobeshona publication division",
  },
  {
    href: "/research/library",
    type: "page",
    titleBn: "লাইব্রেরি ও জার্নাল",
    titleEn: "Library & Journals",
    excerptBn: "গবেষণা লাইব্রেরি, জার্নাল ও ডিজিটাল আর্কাইভ",
    excerptEn: "Research library, journals and digital archive",
    keywords: "library journal archive library digital books",
  },
  {
    href: "/research/projects",
    type: "page",
    titleBn: "গবেষণা প্রকল্প ও ফেলোশিপ",
    titleEn: "Research Projects & Fellowships",
    excerptBn: "চলমান প্রকল্প, কল ফর পেপার্স ও ফেলোশিপ",
    excerptEn: "Ongoing projects, call for papers and fellowships",
    keywords: " projects fellowship call for papers cfp projokto",
  },
  {
    href: "/research/publications",
    type: "page",
    titleBn: "প্রকাশনা ও গ্রন্থপঞ্জি",
    titleEn: "Publications & Bibliography",
    excerptBn: "জার্নাল, গ্রন্থ ও রিসার্চ পেপার",
    excerptEn: "Journals, books and research papers",
    keywords: "publications books prokashona journal papers",
  },
  {
    href: "/research/clarifications",
    type: "page",
    titleBn: "সংশয় নিশ্পাদন ও জবাব",
    titleEn: "Clarifications & Responses",
    excerptBn: "সায়েন্টিজম, নাস্তিক্যবাদ, নারীবাদসহ বিভিন্ন বিষয়ে জবাব",
    excerptEn: "Responses on scientism, atheism, feminism and more",
    keywords: "clarifications shongshoy nispadon jawab response dawah counter",
  },
  {
    href: "/research/fatwa",
    type: "page",
    titleBn: "ফতোয়া ও অনলাইন জিজ্ঞাসা",
    titleEn: "Fatwa & Online Q&A",
    excerptBn: "ফতোয়া ব্যাংক ও প্রশ্ন জিজ্ঞাসার ফরম",
    excerptEn: "Fatwa bank and question submission form",
    keywords: "fatwa fatwa bank question pristiontor mufti sharia",
  },
  {
    href: "/media",
    type: "page",
    titleBn: "মিডিয়া হাব",
    titleEn: "Media Hub",
    excerptBn: "ব্লগ, ভিডিও, খবর ও গ্যালারি",
    excerptEn: "Blog, videos, news and gallery",
    keywords: " media hub blog video news gallery",
  },
  {
    href: "/media/blog",
    type: "page",
    titleBn: "ব্লগ ও আর্টিকেল",
    titleEn: "Blog & Articles",
    excerptBn: "গবেষণাধর্মী আর্টিকেল ও বিশ্লেষণ",
    excerptEn: "Research articles and analysis",
    keywords: "blog articles writeup research article",
  },
  {
    href: "/media/videos",
    type: "page",
    titleBn: "ভিডিও ও পডকাস্ট",
    titleEn: "Videos & Podcasts",
    excerptBn: "ইউটিউব ভিডিও ও অডিও প্রোগ্রাম",
    excerptEn: "YouTube videos and audio programs",
    keywords: "videos youtube podcast lecture",
  },
  {
    href: "/media/news",
    type: "page",
    titleBn: "খবর ও ইভেন্ট",
    titleEn: "News & Events",
    excerptBn: "আসন্ন ইভেন্ট ও পূর্বের খবর",
    excerptEn: "Upcoming events and past news",
    keywords: " news events khobor event",
  },
  {
    href: "/media/gallery",
    type: "page",
    titleBn: "ফটো গ্যালারি",
    titleEn: "Photo Gallery",
    excerptBn: "ক্যাম্পাস ও অনুষ্ঠানের ছবি",
    excerptEn: "Campus and event photographs",
    keywords: "gallery photos album chobi",
  },
  {
    href: "/notices",
    type: "page",
    titleBn: "নোটিশ বোর্ড",
    titleEn: "Notice Board",
    excerptBn: "ভর্তি, নিয়োগ ও একাডেমিক নোটিশ",
    excerptEn: "Admission, recruitment and academic notices",
    keywords: "notice board notish circular",
  },
  {
    href: "/support",
    type: "page",
    titleBn: "সহযোগিতা করুন",
    titleEn: "Support & Donate",
    excerptBn: "যাকাত, স্পন্সর, স্কলারশিপ ও সাধারণ ফান্ড",
    excerptEn: "Zakat, sponsor, scholarship and general funds",
    keywords: "support donate sohojogita dan contribution bkash nagad payment",
  },
  {
    href: "/support/zakat-calculator",
    type: "page",
    titleBn: "যাকাত ক্যালকুলেটর",
    titleEn: "Zakat Calculator",
    excerptBn: "সহজ যাকাত হিসাব — সোনা, রূপা, ব্যবসা ও দেনা",
    excerptEn: "Easy zakat calculation — gold, silver, business and debts",
    keywords: "zakat calculator hisab nisab gold silver sohota",
  },
  {
    href: "/contact",
    type: "page",
    titleBn: "যোগাযোগ",
    titleEn: "Contact",
    excerptBn: "ঠিকানা, ফোন, ইমেইল ও যোগাযোগ ফরম",
    excerptEn: "Address, phone, email and contact form",
    keywords: "contact address phone email jogajog form map",
  },
  {
    href: "/login",
    type: "page",
    titleBn: "লগইন",
    titleEn: "Login",
    excerptBn: "অ্যাকাউন্টে প্রবেশ করুন",
    excerptEn: "Sign in to your account",
    keywords: "login signin account access",
  },
  {
    href: "/register",
    type: "page",
    titleBn: "রেজিস্ট্রেশন",
    titleEn: "Register",
    excerptBn: "নতুন অ্যাকাউন্ট তৈরি করুন",
    excerptEn: "Create a new account",
    keywords: " register signup account create notun",
  },
  {
    href: "/account",
    type: "page",
    titleBn: "আমার অ্যাকাউন্ট",
    titleEn: "My Account",
    excerptBn: "ডোনার ড্যাশবোর্ড ও অনুদানের ইতিহাস",
    excerptEn: "Donor dashboard and donation ledger",
    keywords: "account dashboard donation history receipts",
  },
  {
    href: "/research/fatwa#ask",
    type: "action",
    titleBn: "ফতোয়া জিজ্ঞাসা করুন",
    titleEn: "Ask a Fatwa Question",
    excerptBn: "ইসলামিক প্রশ্ন জমা দিন — দ্রুত জবাব পাবেন",
    excerptEn: "Submit an Islamic question — get a prompt answer",
    keywords: "ask fatwa question submit prosno",
  },
  {
    href: "/support?fund=zakat",
    type: "action",
    titleBn: "যাকাত দিন",
    titleEn: "Give Zakat",
    excerptBn: "১০০% যাকাত ফান্ডে পৌঁছে যায়",
    excerptEn: "100% reaches the zakat fund",
    keywords: "give zakat donate fund",
  },
  {
    href: "/support?fund=sponsor",
    type: "action",
    titleBn: "শিক্ষার্থী স্পন্সর করুন",
    titleEn: "Sponsor a Student",
    excerptBn: "মাসিক ৳৬,০০০ এ একজন শিক্ষার্থীর দায়িত্ব নিন",
    excerptEn: "Take responsibility for a student at ৳6,000/month",
    keywords: " sponsor student child monthly ashor",
  },
];
